name: work-1

on:
  push:
    branches:
      - main

jobs:
  hello-1:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
      
      - name: Say My Name
        run: echo "Triggered by ${{ github.actor }}"
